ARCH=arm64
LLVM=1
LLVM_IAS=1
KBUILD_BUILD_USER="VR4-Team"
KBUILD_BUILD_HOST="Azure-vR4-Valhalla"
KBUILD_COMPILER_STRING="Oₓ (ORx's C Compiler, +pgo, +bolt, +lto, LLVM-based) clang 22.1.8"
KERNEL_NAME="Azure-vR4"
KERNEL_LOCALVERSION="-Azure-vR4"
CROSS_COMPILE="aarch64-linux-gnu-"
KMI_SYMBOL_CHECK="true"
